(autoload 'mutt-save-current-buffer-and-exit    "mutt" "" t)
(autoload 'mutt-delete-quoted-signatures        "mutt" "" t)
(autoload 'mutt-delete-old-citations            "mutt" "" t)
(autoload 'mutt-goto-body                       "mutt" "" t)
(autoload 'mutt-goto-signature                  "mutt" "" t)
(autoload 'mutt-mode                            "mutt" "" t)
(autoload 'headers-mode                         "mutt" "" t)
(autoload 'headers-position-on-value            "mutt" "" nil)
(autoload 'headers-goto-field                   "mutt" "" nil)
(autoload 'define-header-goto                   "mutt" "" t 'macro)
(autoload 'headers-attach-file                  "mutt" "" t)
(provide 'mutt-mode-epackage-autoloads)
